dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip
      - python

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.24.1/bazel-0.24.1-installer-linux-x86_64.sh
  - chmod +x bazel-0.24.1-installer-linux-x86_64.sh
  - ./bazel-0.24.1-installer-linux-x86_64.sh --user
  - export PATH="$PATH:$HOME/bin"

script:
  - bazel build //cmd/poseidon
  - bazel test -- //... -//hack/... -//vendor/... -//test/e2e/...

notifications:
  email: true
    - shivram.srivastava@huawei.com

os:
  - linux
